name: TweetAutomation

on:
  schedule:
    # 8:00 AM Nueva York
    - cron: "0 13 * * *"
    # 8:00 AM Berlín
    - cron: "0 7 * * *"

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run the script
        run: node index.js
